name: Test git_switcher Install and Uninstall

on:
  push:
    branches: [ main, patch-* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Comprehensive git_switcher test (Unix)
      if: runner.os != 'Windows'
      env:
        SHELL: /bin/bash
      run: |
        set -e # Exit immediately if a command exits with a non-zero status
        echo "Current directory: $(pwd)"
        echo "Contents of current directory:"
        ls -R
        ORIGINAL_DIR=$(pwd)
        
        touch ~/.bashrc
        echo "Bash RC file created/ensured"
        
        echo "Installing git_switcher..."
        python install.py
        
        echo "Content of ~/.bashrc:"
        cat ~/.bashrc
        
        # Source bashrc and export functions for use in this script
        source ~/.bashrc
        
        echo "Defined aliases and functions:"
        alias
        declare -F | grep git_switcher
        
        echo "Testing git_switcher functionality..."
        if type git_switcher &>/dev/null; then
          git_switcher --help
        else
          echo "git_switcher not found, using full path"
          $ORIGINAL_DIR/source/git_switcher.py --help
        fi
        
        echo "Uninstalling git_switcher..."
        if type git_switcher_uninstall &>/dev/null; then
          git_switcher_uninstall
        else
          echo "git_switcher_uninstall not found, using full path"
          python $ORIGINAL_DIR/uninstall.py
        fi
        
        echo "Content of ~/.bashrc after uninstall:"
        cat ~/.bashrc
        
        echo "Checking if git_switcher alias still exists..."
        if alias git_switcher 2>/dev/null; then
          echo "git_switcher alias still exists (unexpected)"
          exit 1
        else
          echo "git_switcher alias not found (as expected after uninstall)"
        fi
        
        echo "Checking if installation directory is removed..."
        if [ -d "$ORIGINAL_DIR/source" ] || [ -f "$ORIGINAL_DIR/install.py" ] || [ -f "$ORIGINAL_DIR/uninstall.py" ]; then
          echo "git_switcher files still exist (unexpected)"
          ls -R $ORIGINAL_DIR
          exit 1
        else
          echo "git_switcher files have been removed"
        fi
        
        echo "All tests completed successfully!"
        
        # Recreate the empty directory for post-job cleanup
        mkdir -p "$ORIGINAL_DIR"
        echo "Empty directory recreated for post-job cleanup"
      shell: bash